### ISSUE TITLE
Feature Request - Add Coinbase Support

### ISSUE THREAD

**Issue by computeronix** [trezor/trezor-mcu#101]
Please add Coinbase Wallet Support or work with them to add it :)

https://www.coinbase.com/

**Comment by prusnak** [comment]
There is nothing to be done on the firmware side. Everything is ready.

There is a Javascript platform called TREZOR Connect[1], which main purpose is to make integration of TREZOR into web applications such as exchanges easy. Point Coinbase guys to it as it is their turn to do the integration.

[1] https://github.com/trezor/connect
