### ISSUE TITLE
Release tag v1.3.0 is missing

### ISSUE THREAD

**Issue by schildbach** [trezor/trezor-mcu#12]
Since the license change disaster, the v1.3.0 tag is missing. I suggest adding it back as the same commit hash from before the license change. It should be commit b5eecb30be7712855cfa76fe671ef0b2e98e4aa9.

**Comment by prusnak** [comment]
Right. Forgot to run git push --tags.

Thanks!

**Comment by schildbach** [comment]
Thanks.
