### ISSUE TITLE
Add yubico example u2f to known apps

### ISSUE THREAD

**Issue by runn1ng** [trezor/trezor-mcu#127]
There is this useful u2f example (good for testing)

https://demo.yubico.com/u2f

It's missing in the known apps list

But I have no idea where is the magic string even coming from. It doesn't seem to be any of the parameters that are displayed on the "technical details" page :)

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/trezor-mcu/commit/3cede26fbc1dd5194403f8694323c1efb2426be9
