### ISSUE TITLE
Ethereum - Implement EIP 155

### ISSUE THREAD

**Issue by runn1ng** [trezor/trezor-mcu#142]
We should implement EIP 155 for Ethereum replay attack prevention.

https://github.com/ethereum/EIPs/issues/155

When I looked into the code, I think we are using the old scheme

**Comment by runn1ng** [comment]
cc @axic

**Comment by runn1ng** [comment]
we should also make sure this doesn't break ETC (I am not sure how it works over there...)

**Comment by jhoenicke** [comment]
I can't find if ETC has implemented eip-155 or something else (ecip-1011/1012) ... the web search is a bit confusing.

I will implement eip 155.  I just add a chain_id to the ethereum_sign_tx message.  If that is not set, a (not replay protected) signature in the old format is produced.

**Comment by jhoenicke** [comment]
Note that the chain_id patch is still completely untested.

**Comment by prusnak** [comment]
Implemented in https://github.com/trezor/trezor-mcu/pull/146

Please reopen if problem if issue is not fixed.

**Comment by runn1ng** [comment]
OK, I will try to test this with myetherwallet.

**Comment by runn1ng** [comment]
The EIP code seems to be working. The transaction has correct `v` and the signature is correct. :+1:
