### ISSUE TITLE
segwit branch - "cancel" on the "warning" address screen does nothing

### ISSUE THREAD

**Issue by runn1ng** [trezor/trezor-mcu#159]
If I click "cancel" on the "warning" screen on Segwit "view address", nothing happens.

**Comment by runn1ng** [comment]
cc @jhoenicke

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/trezor-mcu/commit/dcceec806dc0fe2a2259984dc57508fc14a0f4ca
