### ISSUE TITLE
Add Monacoin support

### ISSUE THREAD

**Issue by cryptcoin-junkey** [trezor/trezor-mcu#174]
Monacoin is the most famous cryptcurrency in Japan.
Based on Litecoin and some are from Vertcoin (Lyra2REv2) and from DASH (Dark Gravity Wave).
It has the fork of Insight. So it will fit for Trezor with less difficulty.

I can provide pull requests if this issue is acceptable.

**Comment by cryptcoin-junkey** [comment]
I think this PR is no need to request since parameters for coins are dynamically generated on the build time.
So I close it.

**Comment by prusnak** [comment]
Will be added via https://github.com/trezor/trezor-common/pull/32
