### ISSUE TITLE
Modulo bias when dealing with random numbers

### ISSUE THREAD

**Issue by lukejahnke** [trezor/trezor-mcu#2]
There are a couple of instances of code similar to the following:

    j = random32() % 24;

This should not be used as it creates a tiny bias towards lower numbers (which numbers obviously depends on the divisor used).

More info on this type of issue can be found here: http://stackoverflow.com/a/10984975

**Comment by prusnak** [comment]
Fixed in 349876daffb48a74461d92d8372a8e13587336c2
