### ISSUE TITLE
Trezor pairing with Electrum reports "read error" on OSX

### ISSUE THREAD

**Issue by ManfredKarrer** [trezor/trezor-mcu#204]
Not sure if issue is on Electrum side or Trezors side but in doubt I post here as well (Electrum issue: https://github.com/spesmilo/electrum/issues/2698).

I am using latest Trezor firmware (1.5.0 ) and latest Electrum software (2.9.2) for OSX 10.11.6.
When I setup a new wallet with Trezor it recognize Trezor but then reports a "read error".
Tried both without Trezor wallet page open and Pin entered and without Trezor wallet page open and Pin not entered.

**Comment by prusnak** [comment]
Make sure you don't have trezor bridge (aka trezord) running nor you have trezor web wallet opened in the browser when you use Electrum. Best is to close browser completely to be sure.

**Comment by ManfredKarrer** [comment]
Update: Seems it works now after restarted all. Yes was probably a conflict as Trezor was used before in the default Trezor wallet.
