### ISSUE TITLE
More detailed commit messages

### ISSUE THREAD

**Issue by lichtamberg** [trezor/trezor-mcu#22]
Hi,

First of all: thanks a lot for your really great work!

I would like to help development and also spend some time to learn the code/improve the trezor firmware... I'm not really good at C, but from time to time I try to improve my knowledge about it and also want to understand the changes of the trezor firmware...

Therefore it would be great, if you could describe the changes in the commit message a bit more detailed, so it would be easier to follow... F.e. I cannot understand anything what this commit does: https://github.com/trezor/trezor-mcu/commit/f344ec9c9ba4d784906e239b21cf297b04b7bf4d

I just want to help to improve trezor, which is really a great product!
Thanks!

**Comment by prusnak** [comment]
Please read https://doc.satoshilabs.com/slips/slip-0013.html

We changed the constant from 46 to 13 to reflect the SLIP number.

I'll try to be more verbose in the commit messages in the future  ...
