### ISSUE TITLE
Suggestions for build improvements

### ISSUE THREAD

**Issue by jpz** [trezor/trezor-mcu#222]
Hi, these are just some additional suggestions for build improvements.  I thought I'd write them up to see if the Trezor team think they are worthwhile.  

---

* **build-firmare.sh builds trezor/trezor-mcu master branch, not taking into consideration local modifications or the state of the current branch**

When I was making changes in a few other PRs, I found it difficult to test that I hadn't broken the build, as the build-firmware.sh script would not run against my local changes, but rather the trezor master branch.

This means that a developer might only get to see that they broke the build-firmware.sh build when it actually gets committed to the master branch itself.

An example of a way to address this to would be to mount the current working directory (the root of the local git repo) and use that as the source to be compiled against.

To be even cleaner separation of concerns, it would be better to externalise the `git checkout` and `git submodule update` stages entirely (I've left in the git commands below for the moment).

```
#!/bin/bash
set -e

IMAGE=trezor-mcu-build

# probably worth moving out of the script, included for compatibility
TAG=$1
if [ -n "$TAG" ]; then git checkout $TAG; fi
git submodule update --init

# get the name of the tag, or else the name of the branch
TAG_NAME=$(git name-rev --name-only --tags HEAD --no-undefined 2>/dev/null)
BRANCH_NAME=$(git name-rev --name-only HEAD)
TAG=${TAG_NAME:-${BRANCH_NAME}}

BINFILE=build/trezor-$TAG.bin
ELFFILE=build/trezor-$TAG.elf

docker build -t $IMAGE .
docker run -t -v $(pwd):/build:z $IMAGE /bin/sh -c "\
	cd /build  && \
	make -C vendor/libopencm3 clean && \
	make -C firmware/protob clean && \
	make clean && \
	make -C firmware clean && \
	make -C vendor/libopencm3 && \
	make -C vendor/nanopb/generator/proto && \
	make -C firmware/protob && \
	make && \
	make -C firmware sign && \
	cp firmware/trezor.bin $BINFILE && \
	cp firmware/trezor.elf $ELFFILE"

/usr/bin/env python -c "
from __future__ import print_function
import hashlib
import sys
fn = sys.argv[1]
data = open(fn, 'rb').read()
print('\n\n')
print('Filename    :', fn)
print('Fingerprint :', hashlib.sha256(data[256:]).hexdigest())
print('Size        : %d bytes (out of %d maximum)' % (len(data), 491520))
" $BINFILE
```

* More generally, I noticed that trezor-mcu/firmware/Makefile depends upon trezor/Makefile to be run prior.  This seems to be the opposite of what you'd normally expect which would be to build subdirectories first - and this order of what needs to be built is only really captured in the list of commands to `docker run`, inside build-firmware.sh.  I wonder if the makefiles for trezor/Makefile, trezor/firmware/Makefile and trezor/firmware/protob/Makefile instead should not be combined into a single Makefile at the root level?

* Related to the prior point, the build-firmware.sh seems a bit busy with all the invocations of make on the vendor packages, and it might be worthy of consideration to put into the root Makefile the invocations `$(MAKE) -C vendor/xxx` (as well as  `$(MAKE) -C vendor/xxx clean` in the clean:: section).  This then would reduce the build-firmware.sh to a single make command to run.

**Comment by saleemrashid** [comment]
Since `script/setup` and `script/cibuild` were added, this issue can be closed
