### ISSUE TITLE
Tx fee estimation can be wrong with op_return

### ISSUE THREAD

**Issue by runn1ng** [trezor/trezor-mcu#232]
When transaction has OP_RETURN outputs, the calculation of fee can be wrong

https://github.com/trezor/trezor-mcu/blob/d006ef6bf7edfa2334fa4d03f004aa09d072526a/firmware/signing.c#L594

OP_RETURN output scripts have variable length (from I think 2 up to 41 bytes), this calculation asumes fixed output length.

I am not sure if this can be used for some attack or not

**Comment by runn1ng** [comment]
Perhaps somehow chained with #231 ?

**Comment by runn1ng** [comment]
OP_RETURN is not displayed, so attacker can modify the transaction to include thousands of OP_RETURNs and the user won't detect it, and will force it to pay larger fees?

**Comment by saleemrashid** [comment]
@runn1ng You can have no more than one `OP_RETURN` output per transaction and each `OP_RETURN` output is limited to 80 bytes. Therefore, the most that an attacker could add to the transaction would be 90 bytes (8 bytes for amount, 1 byte for script length, 1 byte for `OP_RETURN`, 80 bytes of data)

**Comment by saleemrashid** [comment]
That would mean that the estimated transaction size would be off by no more than 55 bytes (which seems acceptable to me). Also, we're underestimating the size rather than overestimating, so we would calculate the fee rate as higher rather than lower and be more likely to warn the user.

**Comment by runn1ng** [comment]
Oh, there is just one op-return per tx, I forgot that

**Comment by runn1ng** [comment]
I am closing this, since this seems fine

**Comment by runn1ng** [comment]
> You can have no more than one OP_RETURN output per transaction and each OP_RETURN output is limited to 80 bytes

Hm, that only applies to what is standard, but Trezor still lets you make the transaction, right. It won't relay, but it stil valid transaction, right?

**Comment by saleemrashid** [comment]
@runn1ng While that's true, the below still applies so I don't think this is an issue

> Also, we're underestimating the size rather than overestimating, so we would calculate the fee rate as higher rather than lower and be more likely to warn the user.

**Comment by runn1ng** [comment]
OP_RETURN can also use empty data, which would cause overestimating.

**Comment by jhoenicke** [comment]
Is someone working on this? If not I give it a shot.  It should not be too difficult to get an almost exact estimate (except for the signature length).

**Comment by prusnak** [comment]
@jhoenicke Yes, please give it a shot.

**Comment by prusnak** [comment]
Fixed via #242
