### ISSUE TITLE
locktime is not displayed on device

### ISSUE THREAD

**Issue by runn1ng** [trezor/trezor-mcu#233]
When transaction has locktime, it's not displayed on device.

Adding locktime to non-locktime transaction is not a problem IMO (worse that could happen is that user will not send his coins).

However, attacker can *strip* locktime (or lower it) when user wants a large one.

**Comment by runn1ng** [comment]
Not sure what is the correct behaviour - if we should always display locktime, or only when it's > 0.

Ideally always :), but that will confuse >99% users that don't use it

**Comment by prusnak** [comment]
As discussed internally: we will not show this info on TREZOR.
