### ISSUE TITLE
Add Mozilla u2f checker

### ISSUE THREAD

**Issue by runn1ng** [trezor/trezor-mcu#238]
Mozilla has a new U2F tester page

https://u2f.bin.coffee/

they should have an entry in the FW, if possible

It's Mozilla's - it's linked here - https://wiki.mozilla.org/Security/CryptoEngineering -  and the author has Mozilla job entry on Github - https://github.com/jcjones/u2f.bin.coffee

**Comment by prusnak** [comment]
Closed via 61044b3fc3a422e70f7f9c48e5307bd9ccb97687
