### ISSUE TITLE
v1.3.1 or previous versions fingerprints not matching with releases.json

### ISSUE THREAD

**Issue by anduck** [trezor/trezor-mcu#24]
Building trezor-mcu as instructed gives different fingerprints than what's listed on https://mytrezor.com/data/firmware/releases.json
The json says v1.3.1 fingerprint is 8030e257fc4c75a8f4a0325f8ea37428dd8fc68a5f9ec5f8e2d1a0de328860cc 
and my local build gives 7f55513a8d5ab1ebdd125a123c96cc230ed976993943007d7f2b31e23c05a630

**Comment by prusnak** [comment]
Have you used the Dockerfile checkouted from v1.3.1 git release tag?

**Comment by anduck** [comment]
Yes. It produces different fingerprint.

**Comment by slush0** [comment]
I confirm, my local build now produces 7f555... as well. When I did local builds in time of firmware release, it made correct fingerprint, so obviously something changed in underlying OS (docker does "apt-get update" on fresh installation).

**Comment by anduck** [comment]
Okay. Is there a way to produce the v1.3.1 fingerprint that matches with releases.json one?

**Comment by prusnak** [comment]
I guess that's not easy without the time machine.

**Comment by anduck** [comment]
Then should you guys make a firmware update with a signature that can be verified?

**Comment by slush0** [comment]
There'll be 1.3.3 soon, so I think it won't make sense.

In the meantime we'll think about how to improve our process so this won't happen next time.

**Comment by Pigeons** [comment]
well for starters have the docker config not "apt-get upgrade"

**Comment by prusnak** [comment]
That does not help, because Docker folks can push update via modifying the ubuntu:14.04 tag.

It would make sense to use particular revhash instead of 14.04 tag and don't call the upgrade.

**Comment by jhoenicke** [comment]
The problem is again arm-none-eabi-gcc.  Installing gcc-arm-none-eabi-4_9-2014q4 from https://launchpad.net/gcc-arm-embedded/+download  I could reproduce the 8030e257fc... hash.
