### ISSUE TITLE
Trezor-mcu with Bluetooth Low Energy support

### ISSUE THREAD

**Issue by StarbuckBG** [trezor/trezor-mcu#248]
As a user I would like to have Trezor device with BLE support so I can use it to send transactions with PC, Mac, iOS, Android device without the need of cable connection.

Requirements:
- Use of single SoC (example: http://www.nordicsemi.com/eng/Products/nRF52840) 
- Battery and charging circuit integration
- Implementation of custom service for communication
- Drivers for PC, Mac devices
- iOS/Android API and application

Security:
BLE must be checked for security leaks and possibilities of MitM attack. I have made such an attack few years ago, so it must be considered as a weakness. 

Battery:
BLE uses extremely low battery. The device should be working fine for weeks with a single charge.

Form factor:
Largest elements are the display and the battery, however I think that the current form factor can be kept.

I have taken a look on the code and I think it will be completely compatible with the nRF52 libraries.

**Comment by prusnak** [comment]
We don't plan to include BLE into the design now.
