### ISSUE TITLE
Please add Release v1.6.0

### ISSUE THREAD

**Issue by jonathancross** [trezor/trezor-mcu#249]
beta-wallet.trezor.io offers and upgrade to firmware `v1.6.0` however that version is not tagged here on GitHub.

**Comment by prusnak** [comment]
Commit https://github.com/trezor/trezor-mcu/commit/723cf295a72ce07b96047901bb8c2e461a2488f8 tagged as 1.6.0.

**Comment by jonathancross** [comment]
Thanks!
