### ISSUE TITLE
Bootloader larger than 32KiB

### ISSUE THREAD

**Issue by kensenjiha** [trezor/trezor-mcu#25]
Trying to build the bootloader, generated bootloader.bin is 39kB. gcc-arm-none-eabi 4.9.2.
seems like the trezor-crypto part is too large.

**Comment by jhoenicke** [comment]
For me the bootloader is 24k.  Try again by calling `make clean && make` in the bootloader directory.

Firmware and bootloader compile trezor-crypto with different flags: bootloader enables `USE_PRECOMPUTED_CP=0` to save space.  However, there is no automatic clean before compiling the bootloader, so if you compiled firmware before you get the large crypto library.

**Comment by kensenjiha** [comment]
hmm, I accidentally dropped `-Wl,--gc-sections` while changing `LD` from `gcc` to `ld`. now the size is ~24kB. 
Thanks~
