### ISSUE TITLE
Please add bl1.3.3

### ISSUE THREAD

**Issue by js836** [trezor/trezor-mcu#256]
Bootloader 1.3.3 has not been tagged. It is also missing from the changelog. Furthermore, I would like to request the correct hash for this bootloader version.

**Comment by prusnak** [comment]
Tag https://github.com/trezor/trezor-mcu/tree/bl1.3.3

hash: 8ce8d79edf430c034264686ca9b1d78d26edb2acab7139be8f985c2a3c6cae11
