### ISSUE TITLE
Add CryptoKitties support

### ISSUE THREAD

**Issue by karel-3d** [trezor/trezor-mcu#257]
CryptoKitties are probably the most important Ethereum application. Arguably more important than Dogecoin, since cats > dogs.

Unfortunately, the app is integrated with MetaMask heavily and Metamask doesn't support Trezor yet

See https://github.com/MetaMask/metamask-extension/issues/605

So I am keeping this just as a todo item to add after Metamask adds Trezor support

**Comment by prusnak** [comment]
Let's reopen this once Metamask implements TREZOR support.
