### ISSUE TITLE
Reduce flash erase cycles?

### ISSUE THREAD

**Issue by jhoenicke** [trezor/trezor-mcu#28]
The number of Flash erase cycles is limited.  Usually 10,000 cycles are guaranteed; I can't find the number the STM32F2 guarantees.  For TREZOR this mainly concerns the PIN failure counter.  This must be updated twice for every PIN that was entered.  During this process the TREZOR has to clear the complete configuration sector and write it again.  So after 5,000 PIN entries the flash may stop working, which means that the TREZOR is broken.

My suggestion would be to reserve a big block (say 4096 bytes) in the metadata area just for the PIN failure counters (or just use the full second metadata block).  The format could be as follows.  The block stores 1024 uint32.  The first non-zero entry defines the PIN failure counter, the following entries are `0xffffffff` (the initial value after an erase). The PIN failure counter is `0xffffffff` for 0 failures, `0xfffffffe` for 1 failures `0xfffffffc` for 2 failures and so on. The reason for this format is that one can set a bit to 0 but not to 1 without erasing the flash block.

So the PIN code would find the first non-zero entry.  This is interpreted as a failure counter.  Inverting it will give the number of seconds to wait :).  Then shift it left by one bit and write the result back (check for 0, to avoid setting the failure count to 0 after the 31st try (although this will not happen before the year 2150 anyway)).  Then ask for the PIN.  If PIN was entered correct write a 0 to this value.  This will select the next uint32 containing a `0xffffffff` on the next PIN entry. If the last entry in the PIN data block was written, erase and rewrite the config block.

Maybe I'm a bit paranoid, but I'm currently writing it on a laptop with a four year old SSD that will probably stop working in the next few weeks and is already causing the whole system to hang for several seconds on every write access.

**Comment by prusnak** [comment]
Implemented in https://github.com/trezor/trezor-mcu/pull/82
