### ISSUE TITLE
ethereum_verify_message mixes case on HEX address on Trezor display

### ISSUE THREAD

**Issue by brianddk** [trezor/trezor-mcu#283]
When performing a ethereum_verify_message command on Trezor FW tag v1.6.0, the "Verify Address" message displays the ethereum hex address in mixed case.  Some of the [A-F] are uppercase, while some of the [a-f] are lowercase.

It seems the standard convention for displaying hex is [a-f] lower case.

**Comment by prusnak** [comment]
Ethereum encodes checksum into lowercase-uppercase letters as per [EIP-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md).
