### ISSUE TITLE
Display longer messages and split on word boundaries

### ISSUE THREAD

**Issue by saleemrashid** [trezor/trezor-mcu#286]
While this is a nice-to-have in general, this is essential for supporting BIP70. With BitPay, you will get a memo that begins with `Payment request for BitPay invoice XXXXXXXXXXXXXXXXXXXXXX for merchant `. With `split_message`, that is more than 4 lines and that is not even including the merchant name.

One solution would be to having line-by-line scrolling.

 * On the initial page, the buttons would be `Cancel` and `Scroll down`.
 * On the following pages, the buttons would be `Scroll up` and `Scroll down` which scroll by a single line.
 * On the final page, the buttons would be `Scroll up` and `Confirm`.

Another issue is that we should implement a function that tries to split on word boundaries where possible.

**Comment by prusnak** [comment]
Will be fixed via porting trezor-core to T1.
