### ISSUE TITLE
Bech32 p2wsh addresses don't fit on display

### ISSUE THREAD

**Issue by karel-3d** [trezor/trezor-mcu#289]
Bech32 pwsh addresses currently don't fit on display in most cases.

In examples I tried, it came 2 or 3 letters short.

Examples for example [in BIP173 itself](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#examples)

The problem will maybe be worse in the new bcash address format, if we will implement it

**Comment by prusnak** [comment]
Please test

**Comment by karel-3d** [comment]
Nope, this makes the last line fit, but I realized even the *previous lines* don't fit, since they are longer than the line. (I can't make picture because my phone cam is broken :( )
