### ISSUE TITLE
Decide how to handle new Storage fields

### ISSUE THREAD

**Issue by saleemrashid** [trezor/trezor-mcu#291]
In 045ef22d98e22a19971ad8f6787241a940c2463b, I added macros to generate the Nanopb fields for the `Storage` struct (to maintain compatibility).

Now we no longer use Nanopb, we need to decide whether to continue with the same convention. I think that the `has_` fields are unnecessary and `size_t size` is not needed for fixed-size buffers.

**Comment by prusnak** [comment]
We changed the way to store the data completely in 1.8.0
