### ISSUE TITLE
Incorrect usage of memset in fsm.c?

### ISSUE THREAD

**Issue by roosmaa** [trezor/trezor-mcu#30]
I'm trying to compile the firmware with GCC 5.1 and it complained about the following in
[fsm.c:798](https://github.com/trezor/trezor-mcu/blob/72f2f5ced64bd6eccef3840ad333f2909284d207/firmware/fsm.c#L798-799):
```c
memset(resp->address, sizeof(resp->address), 0);
memset(&(resp->message), sizeof(resp->message), 0);
```

Looks like the arguments order has been mixed up?

**Comment by prusnak** [comment]
Fixed in 02040421cbd1f2716f2f0bbf7077c8f384309afb. Thanks!
