### ISSUE TITLE
Something wrong with ethereum msg signing

### ISSUE THREAD

**Issue by kvhnuke** [trezor/trezor-mcu#312]
PrivKey: `0df7c2cb84b7022491bd48a1e3217f66404850e399f72ab5d2a439e4747ec3ed`
Address: `0x661a35390053d0de80caea5e65d81fd7e6a79e2e`
Msg: `abcdef`

signed through Trezor
Sig: `0x8eb929a9ee288d84f7dc458a3974b980e499f76b33be66e9ce4016e918089cdb0e17b3c1529e90d6ad6bbed19dca26fd36f9b6f1580320c359d0b58db4f40a5d1c`

signed through MEW and geth
Sig: `0xf60b8e7b6b33798e0666eff3000f0f0bd442dfe820660b4aee2e863b2a70611c1f2e78066827c233a28662cbb638493127248374d0657a9a8e761a9f9927d4e51b`

Please look into this and let me know

**Comment by prusnak** [comment]
Sign/Verify message is broken on Ethereum; see https://github.com/ethereum/go-ethereum/issues/14794

This won't be fixed unless there is a consensus in Ethereum community; maybe EIP-712? https://github.com/trezor/trezor-core/issues/122
