### ISSUE TITLE
Build firmware script not building on Ubuntu

### ISSUE THREAD

**Issue by jimbouki** [trezor/trezor-mcu#320]
On Ubuntu I could not build... get following message:
*** No rule to make target '../bootloader/bootloader.bin', needed by 'bl_data.h'. Stop.
make: Leaving directory '/trezor-mcu/firmware'

There was a commit to a Makefile: https://github.com/trezor/trezor-mcu/commit/9588e8f2736b60916f51e470deb18f55112a6ebc that might have something to do with this. Please advise. Thanks.

**Comment by yura-pakhuchiy** [comment]
@jimbouki see https://github.com/trezor/trezor-mcu/pull/321

**Comment by jimbouki** [comment]
Thanks. That makes sense. I was going to compile bootloader separately and see

**Comment by jimbouki** [comment]
Did not mean to do close and reopen. Thanks Yura your changes make sense. I will try.
