### ISSUE TITLE
Apply Flags doesn't commit them to storage

### ISSUE THREAD

**Issue by jhoenicke** [trezor/trezor-mcu#324]
This causes the bug that email settings are not stored.

`fsm_msgApplyFlags`  needs to call `storage_update`.

Or something more elaborate, checking if an update is necessary.

In principle we can also store the flags negated, so that we don't have to erase the flash for each update, but that requires work to get it backwards compatible.

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/trezor-mcu/commit/3a908d7c7da1fd7f64ff0d49f26f75b9bea10803
