### ISSUE TITLE
Remove nem_mosaics.json and use the one from trezor-common

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-mcu#344]
When trezor-common is updated to master (after mergning Lisk and Stellar), remove nem_mosaics.json and modify the nem_mosaics.py script to read the json file from trezor-common

**Comment by prusnak** [comment]
updated trezor-common via https://github.com/trezor/trezor-mcu/commit/a1cde6e0cecc9992593797481f4431b6525b2252 so this can be done now
