### ISSUE TITLE
Screen Flickers On Multiple GetAddresses

### ISSUE THREAD

**Issue by MelbourneDeveloper** [trezor/trezor-mcu#349]
This code gets 50 addresses. The ShowDisplay flag is set to false.

                    for (uint i = 0; i < 50; i++)
                    {
                        var address = await trezorManager.GetAddressAsync("CRW", 72, false, i, false, AddressType.Bitcoin);
                        await Task.Delay(50);
                    }

This is the message:

`new GetAddress { ShowDisplay = false, AddressNs = path, CoinName = GetCoinType(coinShortcut)?.CoinName, ScriptType = isSegwit ? InputScriptType.Spendp2shwitness : InputScriptType.Spendaddress }`

It does this:

Read: Trezor.Address
Write: Trezor.GetAddress
Delay 50 ms
Read: Trezor.Address
Write: Trezor.GetAddress
Delay 50 ms
Read: Trezor.Address
Write: Trezor.GetAddress
Delay 50 ms
Etc.

However, the Trezor screen goes bananas and the user thinks it's glitching out. 

Of course, I could grab the public key, and calculate the addresses myself, but I am telling all of my users that I will never grab the public key off the device, which is a privacy point I am trying to build in to the software.

**Comment by MelbourneDeveloper** [comment]
My recommendation:

Add a message called "StartWaiting". In this mode the screen will say "Waiting..." and have the animation. The screen will not be updated until the "StopWaiting" message is received, OR some critical message like "SignTx" is received.

**Comment by prusnak** [comment]
Fixed in f302b04f311d2a4d0bc2cd3e21eab807857b4a53

**Comment by jhoenicke** [comment]
@prusnak: Have you checked multisig?  IIRC computing multisig addresses sometimes shows the progress dialog, so the layoutHome may be needed for them.

**Comment by prusnak** [comment]
@jhoenicke Good catch, reverted the old fix and fixed differently in 233f2f1cfddde95562b731f46dc35bdf7d122127

**Comment by MelbourneDeveloper** [comment]
Thanks @prusnak and @jhoenicke 

Is there a way I can monitor when this comment will get rolled in to the next firmware release?
