### ISSUE TITLE
Emulator not recognized

### ISSUE THREAD

**Issue by SeunLanLege** [trezor/trezor-mcu#350]
![screenshot from 2018-05-13 17-00-42](https://user-images.githubusercontent.com/16494314/39969112-348578e0-56cf-11e8-84ad-f66daa91b429.png)
successfully built and launched the emulator
installed the bridge daemon

visited trezor.io/start

the emulator isn't recognized :disappointed:

**Comment by alepop** [comment]
@SeunLanLege you should restart `trezord` and run it with params ` -e 21324`
more info [here](https://github.com/trezor/trezord-go#emulator-support)
