### ISSUE TITLE
Stellar: protobuf StellarSignMessage.message is inconsistent with StellarVerifyMessage

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-mcu#353]
The `message` field in the `StellarSignMessage` message is declared as UnicodeType, but as BytesType in `StellarVerifyMessage`.

@prusnak Let's make this consistent and declare both as UnicodeType?

**Comment by prusnak** [comment]
I would say, let's make it consistent with (Bitcoin) [SignMessage](https://github.com/trezor/trezor-common/blob/master/protob/messages.proto#L529)/VerifyMessage and make the field BytesType

**Comment by tsusanka** [comment]
...and done in python-trezor https://github.com/trezor/python-trezor/compare/f97815f69a6a515d0e7ae50554d6f78f1597edaf...master   I hope the `normalize_nfc` usage is correct

**Comment by prusnak** [comment]
Fixed in 29664c4218478a41b063637fc59081534c283a5c
