### ISSUE TITLE
Windows Device Drivers Stacking Up

### ISSUE THREAD

**Issue by MelbourneDeveloper** [trezor/trezor-mcu#359]
After the last firmware/bridge update, my UWP (Windows 10) app stopped being able to connect to the Trezor while my Android app has no issues. I'm still trying to diagnose the problem, but it may be related to this. I currently have two Hid devices installed with the same VID and PID for Trezor. Windows is complaining that there is an ambiguous match. The ID of the device, according to windows changed after the last firmware/bridge upgrade.

It shows up as two distinct "USB Input Devices" under System->Device Manager->Human Interface Devices->

I'm not sure if it's relevant or not, but Windows 10 considers the device to have a different ID to the device before. The old device Id according to Windows 10 was:

\\?\hid#vid_534c&pid_0001&mi_00#7&24a89e25&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

The new ID is:

\\?\USB#VID_534C&PID_0001#2EE5252107F7BF65437A78B1#{a5dcbf10-6530-11d2-901f-00c04fb951ed}

Another piece of information is that I cannot remove the devices. I tried uninstalling at the Windows level, but as soon as I plug the Trezor in, the both reappear. I'm really struggling to get my Windows 10 app running again.

![image](https://user-images.githubusercontent.com/16697547/40881928-99f8a74a-6716-11e8-8bbe-d527d82f07e4.png)

![image](https://user-images.githubusercontent.com/16697547/40881930-afbefd04-6716-11e8-9436-6c3c276629b9.png)

**Comment by prusnak** [comment]
I don't think this is a trezor issue. I'd suggest contacting Microsoft support.

**Comment by MelbourneDeveloper** [comment]
@prusnak you are probably 100% correct. Nevertheless, this problem broke my app. 

Windows is returning 3 Hid Ids for my Trezor:
\\?\USB#VID_534C&PID_0001#2EE5252107F7BF65437A78B1#{a5dcbf10-6530-11d2-901f-00c04fb951ed}
\\?\HID#VID_534C&PID_0001&MI_01#7&1cc30b55&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
\\?\HID#VID_534C&PID_0001&MI_00#7&2ff32793&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}

When I narrowed down the correct Id which is \\?\HID#VID_534C&PID_0001&MI_00#7&2ff32793&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030} the app started working again.

From an app point of view, how can I tell which one is the correct Trezor? The Id changed with the last firmware update. So, this problem is bound to happen again on the next firmware update. I'm currently selecting on Vid and Pid, but this only narrows the choice down to 3 devices, so I need a 3rd part.

Will selecting on "MI_00", be enough to stop the problem from happening on the next firmware update?

**Comment by MelbourneDeveloper** [comment]
According to the shitty Windows 10 API, all these devices **_are_** enabled, but none of them are the **_default_**. So, I'm left taking a wild guess.

**Comment by MelbourneDeveloper** [comment]
@prusnak , actually, the problem is nowhere near as severe as I thought...

I iterated through the three Ids, attempted to connect to each, and then continued on with the one that works. It's allowed me to fix my app and this should be future proof for the next firmware update. Just thought I'd log this in case other experience the same issue.

**Comment by prusnak** [comment]
Yes, select `MI_00` which is guaranteed to be always the right interface.
