### ISSUE TITLE
Canceling "show address" from PC will toggle QR code instead of canceling

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-mcu#360]
it seems that T1 interprets `Cancel` message as "button 2".

That means that when showing address, sending Cancel from PC side will switch between QR code and address text, instead of canceling action.

Test case here: https://github.com/trezor/python-trezor/commit/ff5402842ca5650f70811f4dcb86ce1282fcea34#diff-680dbc8e79e141d1df4f7d7124c28446

**Comment by karel-3d** [comment]
Wasn't this already fixed somewhere? I remember this vaguely

**Comment by karel-3d** [comment]
Oh I am confusing it with

https://github.com/trezor/trezor-mcu/pull/287

**Comment by matejcik** [comment]
that looks like the same issue, yes
however this test fails on current master. I can push it to python-trezor master and make trezor-mcu fail, if you like ;)

**Comment by prusnak** [comment]
Yes, please add the test to python-trezor master.

**Comment by saleemrashid** [comment]
Solution should be as simple as adding a `protectAbortedByCancel`, right?

**Comment by prusnak** [comment]
Fixed as per Saleem's suggestion in df0bad4f09bff651023562e22735ab937a576149
