### ISSUE TITLE
StellarGetPublicKey vs StellarGetAddress

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-mcu#363]
As we discuss,
There should be two independent messages:

1. StellarGetPublicKey which returns StellarPublicKey (without displaying it on device)
2. StellarGetAddress which return StellarAddress and optionally display it on device (depending on show_display variable)

**Comment by tsusanka** [comment]
Just for reference: in core this is done by https://github.com/trezor/trezor-core/issues/226 and https://github.com/trezor/trezor-core/issues/228

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/trezor-mcu/commit/217d5dd01d4b85003ac163fdeae969e07431a237
