### ISSUE TITLE
RSKIP-60 based checksum address encoding

### ISSUE THREAD

**Issue by ilanolkies** [trezor/trezor-mcu#364]
### General
[RSKIP-60](https://github.com/rsksmart/RSKIPs/blob/master/IPs/RSKIP60.md) describes RSK checksum address encoding, compatible with [EIP-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md).

### Benefit
- Allows implementation in any network. 
- Can distinguish between testnets and mainnets.

### Implementation
Etehreum checksum method must receive [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md) chain id.
This changes will impact trezor-crypto.

**Comment by prusnak** [comment]
Please don't create issues like that. Opening a pull request is enough.
