### ISSUE TITLE
Stellar: modify account fields to use addresses

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-mcu#367]
Already merged in trezor-common: https://github.com/trezor/trezor-common/issues/135

To be merged in trezor-core: https://github.com/trezor/trezor-core/commit/6f0d18e1fe8aa4e2d269eeb55aa087c8d294102b

Tests are in python-trezor in the [tsusanka/stellar-accounts-addresses](https://github.com/trezor/python-trezor/tree/tsusanka/stellar-accounts-addresses) branch

**Comment by prusnak** [comment]
python-trezor merged in https://github.com/trezor/python-trezor/commit/10bbb57c865ed514a01daa7b4e821207b62c7f89

**Comment by prusnak** [comment]
This would need much more refactoring than I originally thought :-/

I pushed the trezor-common updated submodule in 2ec6129da5eb1eaa2adae9cc1e283140d1ee19f5 effectively breaking the disabled Stellar code, but we need to refactor that anyway :-/

**Comment by zulucrypto** [comment]
Has anyone started on refactoring this in trezor-mcu? If not, I'll take a stab at it this weekend.

**Comment by prusnak** [comment]
Please do so! Thank you!
