### ISSUE TITLE
Stellar operations do not check if signing process has started

### ISSUE THREAD

**Issue by saleemrashid** [trezor/trezor-mcu#368]
The various `fsm_msgStellar*Op` functions do not check `stellar_signing`. As such, they can be called to perform operations on the private keys, even when the PIN has not been entered.

cc @zulucrypto

**Comment by prusnak** [comment]
JFYI I disabled Stellar in the current master: https://github.com/trezor/trezor-mcu/commit/16ad5ce85401de53864b61afca88e1efebb7219a (it should be pretty easy to re-enable it by doing the reverse operation of the commit).

We'll try to stabilize the code and include it in the next firmware update.

**Comment by zulucrypto** [comment]
@prusnak - Sounds good, would you like me to work on a PR that adds this check or is someone else already on it?

**Comment by prusnak** [comment]
Feel free to do so. Thanks!

**Comment by prusnak** [comment]
I broke the current Stellar code - we'd need to refactor it to use addresses instead of the pubkeys - see https://github.com/trezor/trezor-mcu/issues/367 for more info.
