### ISSUE TITLE
compiling without memory protection MEMORY_PROTECT=0

### ISSUE THREAD

**Issue by juttTechnology** [trezor/trezor-mcu#394]
how you use the MEMORY_PROTECT  in the docker, basically this is the command from docker is  ./build.sh BOOTLOADER_TAG FIRMWARE_TAG.    so we will not use the tag for bootloader and firmware then it will get the latest commmit. finally can we use like ./build.sh MEMORY_PROTECT=0   to disable the memory protection.﻿

**Comment by prusnak** [comment]
just use `MEMORY_PROTECT=0 ./build.sh`

**Comment by saleemrashid** [comment]
@prusnak Does that actually work? I imagine the `MEMORY_PROTECT` doesn't make it into the Docker container.
