### ISSUE TITLE
apt-key adv command in dockerfile might be unsafe

### ISSUE THREAD

**Issue by adrelanos** [trezor/trezor-mcu#4]
From:
https://github.com/trezor/trezor-mcu/blob/master/Dockerfile#L7

The following excerpt might be unsafe.

```
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys FE324A81C208C89497EFC6246D1D8367A3421AFB
```

Because of a gnupg bug. `gpg --recv-keys/--refresh-keys ignores a given long id, uses short ID instead`:
http://bugs.g10code.com/gnupg/issue1340

See also:
http://www.asheesh.org/note/debian/short-key-ids-are-bad-news.html

As a fix you could check that you got the correct key by running:
```
gpg --fingerprint FE324A81C208C89497EFC6246D1D8367A3421AFB
```
and break on non-zero exit codes.

**Comment by prusnak** [comment]
Fixed in 95486eb8b85de6ad0ed693f4225f59af52ab2f0b
