### ISSUE TITLE
Implement support for EIP-712

### ISSUE THREAD

**Issue by rmeissner** [trezor/trezor-mcu#401]
Currently there is no consensus on how to properly sign messages. EIP-712 proposes a new standard.

EIP-712: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md

Issue for Model T: https://github.com/trezor/trezor-core/issues/122

Reference: https://github.com/trezor/trezor-mcu/issues/312

**Comment by prusnak** [comment]
If you plan to implement this, I suggest you start with Model T first, then proceed by creating an unit test in python-trezor similar to https://github.com/trezor/python-trezor/blob/master/trezorlib/tests/device_tests/test_msg_ethereum_signmessage.py

**Comment by marc0olo** [comment]
@prusnak could you elaborate the necessary steps to implement this feature in a bit more detail? if there is nobody that tackles this I might give it a try

but I neither developed for trezor nor have much experience with python. so I need a few hints what needs to be done

**Comment by prusnak** [comment]
We switch to the monorepo, please send PR there: https://github.com/trezor/trezor-firmware
