### ISSUE TITLE
MacOS emulator support

### ISSUE THREAD

**Issue by backslash47** [trezor/trezor-mcu#405]
Hello, 

is there a way how to run the emulator under MacOS?

**Comment by prusnak** [comment]
It might work. Try running `EMULATOR=1 ./script/fullbuild`, but this was never tested before.

**Comment by backslash47** [comment]
Thanks. I was able to build the emulator and run it under MacOS with some small modifications to the build script.

**Comment by prusnak** [comment]
Please share the modifications here, so others can see it too, when they hit the same issues.

**Comment by backslash47** [comment]
No problem.

1. Both sdl2 and sdl2_image needs to be installed using Homebrew.
2. Apply this patch: https://gist.github.com/backslash47/fee8f1229f68aa6dd1f952d0cc70b4a9
3. Build with EMULATOR=1 TREZOR_TRANSPORT_V1=1 DEBUG_LINK=1 ./script/cibuild
    - it will fail because trezor.bin is not there, but the emulator is called trezor.elf
4. run with ./firmware/trezor.elf

**Comment by backslash47** [comment]
2. OK, that's working
3. fullbuild requires commit hashes as parameters, what should I give them?

**Comment by prusnak** [comment]
`./script/fullbuild HEAD HEAD`

**Comment by backslash47** [comment]
Ok, the final required steps are:

1. `brew install sdl2 sdl2_image coreutils`
2. apply patch https://gist.github.com/backslash47/fee8f1229f68aa6dd1f952d0cc70b4a9
3. `EMULATOR=1 TREZOR_TRANSPORT_V1=1 DEBUG_LINK=1 ./script/fullbuild HEAD HEAD`
