### ISSUE TITLE
add Ontology support

### ISSUE THREAD

**Issue by backslash47** [trezor/trezor-mcu#406]
Hi,

I would like to add support to Trezor One for Ontology while you are finalising new firmware for Trezor T. 

As discussed in other thread, I was able to start the emulator for Trezor One. What would be the next steps please?

**Comment by prusnak** [comment]
We don't plan to add any more coins to trezor-mcu codebase. Rather we
would like to port trezor-core to T1 devices.

**Comment by backslash47** [comment]
Is the porting an already undergoing project?
