### ISSUE TITLE
Bitcoin cash address is trimmed on Trezor screen during Verify message confirmation

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-mcu#408]
Trezor One, firmware 1.6.2 and higher. 

1. Switch currency to Bitcoin Cash
2. Go to Sign& Verify
3. Verify a message
4. The last 3 characters of the address are not displayed on Trezor screen

![photo_2018-09-06_11-33-15](https://user-images.githubusercontent.com/31442634/45149144-2e695d00-b1c9-11e8-8e6b-0ae8d9548056.jpg)

The complete address in this example is qryzkswwsgu9hq2d2853a540qt9s9x69yyjh4dkhrn

**Comment by prusnak** [comment]
Yes, we missed that. I'll fix this.

**Comment by prusnak** [comment]
Closed via a3555b9c7cbb616f1cfc6c436726d33075e15034

Thanks for the report!
