### ISSUE TITLE
Firmware build with Docker is too big

### ISSUE THREAD

**Issue by karel-3d** [trezor/trezor-mcu#413]
I tried to build firmware with Docker (with the two PRs I sent - #411, #412). The resulting firmware is too big to load on my trezor, it shows this when I try to load it

![img_20180916_133815](https://user-images.githubusercontent.com/104945/45593700-0d1d2380-b9b6-11e8-8044-9590029b6a3a.jpg)

**Comment by prusnak** [comment]
You need to upgrade to fw 1.6.3 first. This will install bootloader
1.5.1, which can install firmware 1.7.0 and later.

**Comment by karel-3d** [comment]
Correct. Closing
