### ISSUE TITLE
What is the purpose of unfinished_bakup?

### ISSUE THREAD

**Issue by meat00** [trezor/trezor-mcu#415]
https://github.com/trezor/trezor-mcu/blob/bf266f0fd9db73ac71c1356eccbb0eb59dad36e9/firmware/fsm_msg_common.h#L70
 looks like this line of code should be `resp->has_unfinished_backup = true;  resp->unfinished_backup = storage_unfinishedBackup();`

**Comment by prusnak** [comment]
Fixed in https://github.com/trezor/trezor-mcu/commit/9afaeff36ff891ab9dbe48b0f514a273975f8cd0

Thanks!
