### ISSUE TITLE
when run: ./build-emulator.sh, get error ImportError: No module named 'click'

### ISSUE THREAD

**Issue by seelezlk** [trezor/trezor-mcu#417]
~/trezor-mcu$ sudo ./build-emulator.sh
Sending build context to Docker daemon  146.6MB
Step 1/7 : FROM debian:9
 ---> f2aae6ff5d89
Step 2/7 : RUN apt-get update &&     apt-get install -y     build-essential curl unzip git python3 python3-pip     libsdl2-dev libsdl2-image-dev
 ---> Using cache
 ---> eef258c0c56b
Step 3/7 : ENV PROTOBUF_VERSION=3.4.0
 ---> Using cache
 ---> 20fa531fb6b7
Step 4/7 : RUN curl -LO "https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip"
 ---> Using cache
 ---> cf126254ad21
Step 5/7 : RUN unzip "protoc-${PROTOBUF_VERSION}-linux-x86_64.zip" -d /usr
 ---> Using cache
 ---> e7be8811ae59
Step 6/7 : RUN pip3 install "protobuf==${PROTOBUF_VERSION}" ecdsa
 ---> Using cache
 ---> 9570c8e7e7df
Step 7/7 : RUN ln -s python3 /usr/bin/python
 ---> Using cache
 ---> 444dd5da8d88
Successfully built 444dd5da8d88
Successfully tagged trezor-mcu-build-emulator64:latest
Cloning into 'trezor-mcu'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 6098 (delta 13), reused 19 (delta 9), pack-reused 6068
Receiving objects: 100% (6098/6098), 2.37 MiB | 3.08 MiB/s, done.
Resolving deltas: 100% (4537/4537), done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Submodule 'libopencm3' (https://github.com/libopencm3/libopencm3.git) registered for path 'vendor/libopencm3'
Submodule 'vendor/nanopb' (https://github.com/nanopb/nanopb.git) registered for path 'vendor/nanopb'
Submodule 'trezor-common' (https://github.com/trezor/trezor-common.git) registered for path 'vendor/trezor-common'
Submodule 'trezor-crypto' (https://github.com/trezor/trezor-crypto.git) registered for path 'vendor/trezor-crypto'
Submodule 'trezor-qrenc' (https://github.com/trezor/trezor-qrenc.git) registered for path 'vendor/trezor-qrenc'
Cloning into '/trezor-mcu/vendor/libopencm3'...
Cloning into '/trezor-mcu/vendor/nanopb'...
Cloning into '/trezor-mcu/vendor/trezor-common'...
Cloning into '/trezor-mcu/vendor/trezor-crypto'...
Cloning into '/trezor-mcu/vendor/trezor-qrenc'...
Submodule path 'vendor/libopencm3': checked out 'b0e050d10d12c42be031c34822117cfd3c5a0ea7'
Submodule path 'vendor/nanopb': checked out 'cdb61612197feca5391593d051c8d4892e940228'
Submodule path 'vendor/trezor-common': checked out '41e4a84b5b01d03e980f84fab29c8f0b0ec948f5'
Submodule path 'vendor/trezor-crypto': checked out 'f9523f97df2c965835001d551738bbe1b93b53df'
Submodule path 'vendor/trezor-qrenc': checked out '4da44cacb7bd69aa297bafe4a41c498a050225a4'
make: Entering directory '/trezor-mcu/vendor/nanopb/generator/proto'
protoc --python_out=. nanopb.proto
protoc --python_out=. plugin.proto
make: Leaving directory '/trezor-mcu/vendor/nanopb/generator/proto'
make: Entering directory '/trezor-mcu/firmware/protob'
  PROTOC  messages_pb2.py
  PROTOC  messages-bitcoin.pb
  NANOPB  messages-bitcoin.pb.c
Writing to messages-bitcoin.pb.h and messages-bitcoin.pb.c
  PROTOC  messages-common.pb
  NANOPB  messages-common.pb.c
Writing to messages-common.pb.h and messages-common.pb.c
  PROTOC  messages-crypto.pb
  NANOPB  messages-crypto.pb.c
Writing to messages-crypto.pb.h and messages-crypto.pb.c
  PROTOC  messages-debug.pb
  NANOPB  messages-debug.pb.c
Writing to messages-debug.pb.h and messages-debug.pb.c
  PROTOC  messages-ethereum.pb
  NANOPB  messages-ethereum.pb.c
Writing to messages-ethereum.pb.h and messages-ethereum.pb.c
  PROTOC  messages-management.pb
  NANOPB  messages-management.pb.c
Writing to messages-management.pb.h and messages-management.pb.c
  PROTOC  messages-nem.pb
  NANOPB  messages-nem.pb.c
Writing to messages-nem.pb.h and messages-nem.pb.c
  PROTOC  messages.pb
  NANOPB  messages.pb.c
Writing to messages.pb.h and messages.pb.c
  PROTOC  messages-stellar.pb
  NANOPB  messages-stellar.pb.c
Writing to messages-stellar.pb.h and messages-stellar.pb.c
  PROTOC  messages-lisk.pb
  NANOPB  messages-lisk.pb.c
Writing to messages-lisk.pb.h and messages-lisk.pb.c
  PROTOC  messages_nem_pb2.py
rm messages.pb messages-common.pb messages-bitcoin.pb messages-nem.pb messages-ethereum.pb messages-stellar.pb messages-crypto.pb messages-lisk.pb messages-management.pb messages-debug.pb
make: Leaving directory '/trezor-mcu/firmware/protob'
  DEP     gen/fonts.d
  DEP     gen/bitmaps.d
  DEP     winusb.d
  DEP     webusb.d
  DEP     usb21_standard.d
  DEP     supervise.d
  DEP     memory.d
  DEP     util.d
  DEP     serialno.d
  DEP     rng.d
  DEP     oled.d
  DEP     layout.d
  DEP     buttons.d
  CC      buttons.o
  CC      layout.o
  CC      oled.o
  CC      rng.o
  CC      serialno.o
  CC      util.o
  CC      memory.o
  CC      supervise.o
  CC      usb21_standard.o
  CC      webusb.o
  CC      winusb.o
  CC      gen/bitmaps.o
  CC      gen/fonts.o
  AR      libtrezor.a
make: Entering directory '/trezor-mcu/emulator'
  DEP     strl.d
  DEP     udp.d
  DEP     timer.d
  DEP     rng.d
  DEP     oled.d
  DEP     flash.d
  DEP     buttons.d
  DEP     setup.d
  CC      setup.o
  CC      buttons.o
  CC      flash.o
  CC      oled.o
  CC      rng.o
  CC      timer.o
  CC      udp.o
  CC      strl.o
ar rcs libemulator.a setup.o buttons.o flash.o oled.o rng.o timer.o udp.o strl.o
make: Leaving directory '/trezor-mcu/emulator'
make: Entering directory '/trezor-mcu/firmware'
  DEP     protob/messages-lisk.pb.d
  DEP     protob/messages-stellar.pb.d
  DEP     protob/messages-nem.pb.d
  DEP     protob/messages-management.pb.d
  DEP     protob/messages-ethereum.pb.d
  DEP     protob/messages-debug.pb.d
  DEP     protob/messages-crypto.pb.d
  DEP     protob/messages-common.pb.d
  DEP     protob/messages-bitcoin.pb.d
  DEP     protob/messages.pb.d
  DEP     ../vendor/nanopb/pb_encode.d
  DEP     ../vendor/nanopb/pb_decode.d
  DEP     ../vendor/nanopb/pb_common.d
  DEP     ../vendor/trezor-qrenc/qr_encode.d
  DEP     ../vendor/trezor-crypto/nem.d
  DEP     ../vendor/trezor-crypto/aes/aes_modes.d
  DEP     ../vendor/trezor-crypto/aes/aestab.d
  DEP     ../vendor/trezor-crypto/aes/aeskey.d
  DEP     ../vendor/trezor-crypto/aes/aescrypt.d
  DEP     ../vendor/trezor-crypto/hasher.d
  DEP     ../vendor/trezor-crypto/groestl.d
  DEP     ../vendor/trezor-crypto/blake2b.d
  DEP     ../vendor/trezor-crypto/blake256.d
  DEP     ../vendor/trezor-crypto/sha3.d
  DEP     ../vendor/trezor-crypto/sha2.d
  DEP     ../vendor/trezor-crypto/ripemd160.d
  DEP     ../vendor/trezor-crypto/cash_addr.d
  DEP     ../vendor/trezor-crypto/segwit_addr.d
  DEP     ../vendor/trezor-crypto/base58.d
  DEP     ../vendor/trezor-crypto/base32.d
  DEP     ../vendor/trezor-crypto/pbkdf2.d
  DEP     ../vendor/trezor-crypto/bip39.d
  DEP     ../vendor/trezor-crypto/bip32.d
  DEP     ../vendor/trezor-crypto/hmac.d
  DEP     ../vendor/trezor-crypto/ed25519-donna/ed25519-keccak.d
  DEP     ../vendor/trezor-crypto/ed25519-donna/ed25519-sha3.d
  DEP     ../vendor/trezor-crypto/ed25519-donna/curve25519-donna-scalarmult-base.d
  DEP     ../vendor/trezor-crypto/ed25519-donna/ed25519.d
  DEP     ../vendor/trezor-crypto/ed25519-donna/ed25519-donna-impl-base.d
  DEP     ../vendor/trezor-crypto/ed25519-donna/ed25519-donna-32bit-tables.d
  DEP     ../vendor/trezor-crypto/ed25519-donna/ed25519-donna-basepoint-table.d
  DEP     ../vendor/trezor-crypto/ed25519-donna/modm-donna-32bit.d
  DEP     ../vendor/trezor-crypto/ed25519-donna/curve25519-donna-helpers.d
  DEP     ../vendor/trezor-crypto/ed25519-donna/curve25519-donna-32bit.d
  DEP     ../vendor/trezor-crypto/memzero.d
  DEP     ../vendor/trezor-crypto/rand.d
  DEP     ../vendor/trezor-crypto/nist256p1.d
  DEP     ../vendor/trezor-crypto/secp256k1.d
  DEP     ../vendor/trezor-crypto/curves.d
  DEP     ../vendor/trezor-crypto/ecdsa.d
  DEP     ../vendor/trezor-crypto/bignum.d
  DEP     ../vendor/trezor-crypto/address.d
  DEP     debug.d
  DEP     lisk.d
  DEP     stellar.d
  MAKO    nem_mosaics.c
Traceback (most recent call last):
  File "../vendor/trezor-common/tools/cointool.py", line 15, in <module>
    import click
ImportError: No module named 'click'
  DEP     nem2.d
  MAKO    ethereum_tokens.c
Traceback (most recent call last):
  File "../vendor/trezor-common/tools/cointool.py", line 15, in <module>
    import click
ImportError: No module named 'click'
  DEP     ethereum.d
  DEP     crypto.d
  DEP     signing.d
  DEP     reset.d
  DEP     recovery.d
  DEP     layout2.d
  DEP     protect.d
  DEP     transaction.d
  MAKO    coin_info.c
Traceback (most recent call last):
  File "../vendor/trezor-common/tools/cointool.py", line 15, in <module>
    import click
ImportError: No module named 'click'
  DEP     coins.d
  DEP     fsm.d
  DEP     pinmatrix.d
  DEP     trezor.d
  DEP     storage.d
  DEP     messages.d
  DEP     u2f.d
  DEP     udp.d
  MAKO    nem_mosaics.c
Traceback (most recent call last):
  File "../vendor/trezor-common/tools/cointool.py", line 15, in <module>
    import click
ImportError: No module named 'click'
  MAKO    ethereum_tokens.c
Traceback (most recent call last):
  File "../vendor/trezor-common/tools/cointool.py", line 15, in <module>
    import click
ImportError: No module named 'click'
  MAKO    coin_info.c
Traceback (most recent call last):
  File "../vendor/trezor-common/tools/cointool.py", line 15, in <module>
    import click
ImportError: No module named 'click'
  CC      udp.o
  MAKO    coin_info.h
Traceback (most recent call last):
  File "../vendor/trezor-common/tools/cointool.py", line 15, in <module>
    import click
ImportError: No module named 'click'
Makefile:121: recipe for target 'coin_info.h' failed
make: *** [coin_info.h] Error 1
make: Leaving directory '/trezor-mcu/firmware'

**Comment by seelezlk** [comment]
BTW, I have already run the ./build.sh, it seems to work well

**Comment by prusnak** [comment]
Quick fix pushed in 7ab36d57abe20a7b2c746e187f5f95378280ef87

@matejcik feel free to fix it more properly (using pipenv?) if you have some spare cycles
