### ISSUE TITLE
Ubuntu 16.04.5 Desktop need to [ sudo apt-get install libsdl2-2.0-0 ]

### ISSUE THREAD

**Issue by sarveshwar-singh** [trezor/trezor-mcu#421]
On Ubuntu 16.04.5 Desktop need to `sudo apt-get install libsdl2-2.0-0` before `sudo ./build.sh EMU`

**Comment by prusnak** [comment]
This doesn't make sense. `./build.sh` builds using Docker and this installs sdl2 into the image.

**Comment by sarveshwar-singh** [comment]
Followed:
https://github.com/trezor/trezor-mcu/blob/master/README.md

default branch is `master` so i was using `master` on a fresh Ubuntu, tried about two times.

For now I am using Trezor T, after Firmware update of Trezor One which is going support Cardano will try to reproduce.

**Comment by karel-3d** [comment]
`./build.sh EMU` indeed uses docker, I just tried it

However, at the end, it writes an error `install: cannot stat '/src/build/firmware/firmware/trezor-emulator.bin': No such file or directory`. Not sure if related to the OP.

**Comment by karel-3d** [comment]
Oh, but @sarveshwar-singh is right, you still need libsdl2-2.0-0 to RUN the emulator after build
