### ISSUE TITLE
Bitcoin: Arbitrary scripts

### ISSUE THREAD

**Issue by greenaddress** [trezor/trezor-mcu#431]
We can currently use the TREZOR ONE HID API to sign our GreenAddress multisig inputs using setMultisig with a  MultisigRedeemScriptType. 

For CSV support our spending conditions look very different to a standard multisig, and it doesn't seem possible to sign arbitrary scripts with the API available. Are we missing something, or is this not supported yet? Any ETA on if/when it would be supported?

Thanks!

**Comment by prusnak** [comment]
Signing arbitrary scripts is not supported. We will implement PBST in the future, but no ETA for now.
