### ISSUE TITLE
If you set/change PIN you are asked to enter it again on the next action (Label Change)

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-mcu#434]
How to reproduce: 
1) Go to Basic Settings -> PIN protection
2) Change/Enable PIN
3) Go to Label -> Change Label
Result: You are required to enter PIN again. 

<img width="599" alt="screen shot 2018-12-04 at 11 24 40" src="https://user-images.githubusercontent.com/31442634/49436463-7f352580-f7b9-11e8-859f-4f53c5d34d2b.png">

**Comment by prusnak** [comment]
Fixed in fa3481e37d528794adb3b234855c23300782ad92
