### ISSUE TITLE
idea: SessionRequest/SessionAck

### ISSUE THREAD

**Issue by keepkeyjon** [trezor/trezor-mcu#446]
I've been thinking about how to make the session management stuff better: https://github.com/trezor/trezor-mcu/blob/7dce7bd92d65726e08e0311f9821f6cc966b44a1/firmware/fsm_msg_common.h#L24-L36  Did you consider adding something like a `SessionRequest`/`SessionAck` to force the client to attest that it is *the* client having the current conversation with the device, besides just for the `Initialize` message?

One could take this a step further and give the client an ephemeral key, which is used to sign a challenge-response ahead of every message, or even just outright encrypt the entire transport.

Obvious big downsides to doing any of this is that it immediately breaks every other 3rd party integration.

**Comment by prusnak** [comment]
We'll be changing the protocol completely in the future
