### ISSUE TITLE
allow core entropy entry through pin pad

### ISSUE THREAD

**Issue by tphyahoo** [trezor/trezor-mcu#45]
Rather than trust host computer for source of entropy, allow user to generate entropy via alternative means (eg diceware, flipping coins, or however).

The entropy would be entered via the scrambled pin mechanism. If we just use digits 1-8, 256 bits would be 32 entries, or 128 bits would be 16. A bit of a pain, but not too bad. The entropy entry could be repeated to ensure no mistakes.

(For stylepoints, trezor could add a "hexadecimal pin pad" to slyly hint that only 3l1te experts should be using this feature.)

After the entropy entry the 3*x word passphrase would be calculated and displayed to user as usual. The user could can now either

-- throw away the entropy seed, and do future restores with current mechanism
-- or keep the entropy seed, and do future restores with extra secure mechanism of re-entering same entropy via keypad, so even if host computer is compromised the original entropy is maintained, and we don't leak down to 24 factorial, or however many if an attacker gains a scrambled word list.

As a side note on naming, I would refer to "core entropy seed" described above, versus "stretched entropy seed" which is encoded by the pass phrase that is usually referred to as the seed.

For everyone who has ever wondered if /dev/random is back doored on their system, the trezor now presents an irresistible value proposition.

originally submitted to https://github.com/trezor/python-trezor/issues/44

UPDATE:

When I posted this I thought trezor only used external entropy, from connected (possibly backdoored) computer.

I've since learned Trezor already uses both internal and external entropy.

I still think this would be good to have, but less urgent.

Anyways: this is needed if you trust neither the connected computer, nor the trezor's hardware entropy, from being backdoored.

UPDATE 2:

One can of course, always add entropy by selecting a passphrase with as many bits as one wants.

This is however cumbersome compared to specifying the additional entropy at startup, and then only needing to remember a pin. 

Also the passphrase gets entered on an insecure computer, so there's that.

Breadcrumb for starting task: 

https://www.reddit.com/r/TREZOR/comments/2ewgt4/right_now_do_we_have_to_trust_trezor/ckjqthj

UPDATE: 

A good case for why one might want just seed phrase and pin (and not secondary passphrase) is here:

https://standardcrypto.wordpress.com/2016/01/19/if-you-cant-provision-a-good-hiding-place-for-your-hardware-wallet-seed-phrase-maybe-you-dont-need-to-back-it-up-in-the-first-place-use-multiple-wallets-plus-pin-instead/

Reason 1: compatibility with other HW wallets, like ledger wallet.
Reason 2: 2nd factor pin is secure against hacked computer, because scrambled.  secondary passphrase is not secure against hacked computer.

**Comment by nullbio** [comment]
This is actually the only reason I haven't bought a Trezor yet.

**Comment by saleemrashid** [comment]
@nullbio You could provide half the entropy via the computer. If you really want this feature, what entropy source are you going to use? A dice?

**Comment by nullbio** [comment]
@saleemrashid Yeah, dice or something of that kind.

**Comment by mokshasoft** [comment]
I don't know how the device generates entropy, but one thing that could be added is to be able to generate it by clicking the two buttons on the trezor. So the first time you set it up you would have to click the buttons for a minute or so.

**Comment by prusnak** [comment]
Nobody picked that up
