### ISSUE TITLE
Safety check failed error after upgrading to 1.8.0

### ISSUE THREAD

**Issue by rodrigopavezi** [trezor/trezor-mcu#465]
Hi There,
I have upgraded Trezor firmware to 1.8.0 but then now I am getting the following error.

[trezor-link] Calling BridgeTransport.call( 382 EthereumSignTx { address_n: [ 2147483692, 2147483708, 2147483648, 0, 0 ],
nonce: '05',
gas_price: '0165a0bc00',
gas_limit: '5208',
to: '23d233933c86f93b74705cf0d236b39f474249f8',
value: '09184e72a000',
chain_id: 3 } false )

Error:

[trezor-link] Done BridgeTransport.call, result { type: 'Failure',
message:
{ code: 'Failure_DataError', message: 'Safety check failed' } }

Does anyone know what could be happening?

Cheers

**Comment by prusnak** [comment]
Contact our support at https://trezor.io/troubleshooter

**Comment by prusnak** [comment]
Not sure what wallet you are using, but if they are not using Connect 7, tell them to upgrade. This is not a Trezor issue.

**Comment by rodrigopavezi** [comment]
@prusnak I am developer of the SelfKey Wallet which is an electron app. I am not sure Connect 7 will work well with our UX. So we are using trezor.js still. Is there someone from Connect 7 that could help me to understand how I can migrate to it. I need to listen for events like REQUEST_PIN so handling that in our UI then send the PIN to the device callback. I could not find a way of doing that yet.

Cheers

**Comment by prusnak** [comment]
Don't use trezor.js directly. Use Connect. If you have trouble with using Connect from Electron, ask here: https://github.com/trezor/connect/issues/245

**Comment by sk91** [comment]
@prusnak since electron is not supported yet with trezor connect, is there a way to use trezor.js with this? We have an app in production that depends on this integration.

**Comment by sk91** [comment]
please reopen it, it is still an issue

**Comment by prusnak** [comment]
It is not a trezor-mcu issue. The issue is in your code.

Please help us get Connect working on Electrum. That's the only way how to resolve this.

**Comment by tayvano** [comment]
I left a comment here: https://github.com/trezor/connect/issues/245

Hopefully others in this thread can join the conversation as well on 245. Thanks
