### ISSUE TITLE
IDEA: replace pressing two buttons with just one to enter bootloader

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-mcu#466]
Pressing both buttons and plugging in a cable might be quite hard for some users. This was brought up by Honza from support team. We should consider using just one button.

**Comment by prusnak** [comment]
Actually, this is already for bootloader 1.8.0 (shipped with the latest firmware update).

**Comment by prusnak** [comment]
Relevant commit: https://github.com/trezor/trezor-mcu/commit/806f943116f4df8a666b6bd7182bfcbe5cf3c13a

**Comment by tsusanka** [comment]
Ah, cool. We should communicate this to marketing/support/wiki. I guess there is no reason not to make this "more public", right?

**Comment by prusnak** [comment]
Yes, let's tell everyone.
