### ISSUE TITLE
Display mBTC/bits

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-mcu#54]
Title says it all

**Comment by bitsol** [comment]
Display before signing?
Should this be configurable?

**Comment by bitsol** [comment]
https://github.com/trezor/trezor-mcu/blob/cd763b979b0001d4e23fffaf68fa59cfe483a6ba/firmware/layout2.c#L190
Should the change be implemented in layoutConfirmTx(), or a "lower-level" function?
In other words, count me in.

**Comment by prusnak** [comment]
Should be configurable, the preferred format should be stored in Storage.

Yes, `layoutConfirmTx` should be a good place to perform the change.

**Comment by bitsol** [comment]
Sorry, I'm not really familiar with the organization of the source tree. Where should I define the enum, or for that matter, any type of configuration variable?

**Comment by bitsol** [comment]
I just realized how easy it is to get around the `storage.c` file.
https://github.com/trezor/trezor-mcu/blob/bd660655ee26711bcba8d25d6555cc8246e7e2df/firmware/storage.c#L490
This is the kind of function I would write, and then read that value in `layoutConfirmTx`. Is that good?

**Comment by saleemrashid** [comment]
I actually have a branch offline that does this (except for the `Storage` changes). Shall I push that up?

**Comment by bitsol** [comment]
@prusnak thoughts?
I didn't get here fast enough I guess...

**Comment by prusnak** [comment]
@bitsol please check pull request by Saleem here: https://github.com/trezor/trezor-mcu/pull/292

Closing this issue in favor of that PR. Let's continue discussion there.
