### ISSUE TITLE
PIN delay increase may be at risk

### ISSUE THREAD

**Issue by didtoo** [trezor/trezor-mcu#6]
Moved from Reddit forum:
I was just wondering, when the TREZOR is in hostile hands, is it possible to disable memory writing (by a hardware hack or suppling a limited voltage/current), so the delay can not be written or to power down the TREZOR just before the delay is written?
A possible solution would be to always write the delay increase to memory (and verify the write is successful), if correct PIN is given, reset the pin delay by writing 0 seconds after the first write. This is a crucial part of the TREZOR security that needs to be working as advertised.

It looks like a possible weakness in protect.c:
Put something like this before line 164:
```
wait = storage_getPinFails();
storage_increasePinFails();
if (wait >= storage_getPinFails()) {
     fsm_sendFailure(FailureType_Failure_PinInvalid, "Device PIN Failure");
     return false;
}
```
...and something has to be done so getPinFails always reads from flash (perhaps with parameter if slow), not just the buffer.
And remove line 169 could probably fix the issue (make it more fail-safe).

P.S. Should line 317 in storage.c not be (although you can do without the boolean altogether (but that would probably make a firmware update more difficult)):
```
storage.has_pin_failed_attempts = false;
```

**Comment by np** [comment]
What's blocking this issue to be resolved? @didtoo is right.

**Comment by slush0** [comment]
Nothing, it's scheduled for 1.3.1 release.

**Comment by prusnak** [comment]
Fixed in 7dacfd69eeb5b021ab58490105bc1c9e50edf1f1.

TREZOR will halt if there is a problem writing to flash.

**Comment by prusnak** [comment]
@didtoo I think there does not need to be a special treatment for the PIN case and that halting when there is flash failure is enough. Do you agree?

Also wrt to your PS about line 317. Setting

```
storage.has_pin_failed_attempts = false;
```

and

```
storage.has_pin_failed_attempts = true;
storage.pin_failed_attempts = 0;
```

has the same effect because of the behaviour of getPinFails function:

```
return storage.has_pin_failed_attempts ? storage.pin_failed_attempts : 0;
```

**Comment by prusnak** [comment]
Should be fixed by these three commits:
* 7dacfd69eeb5b021ab58490105bc1c9e50edf1f1 (check for flash operation failure)
* 012d38a9a03d4674a54e32e4b9437092b4c047b3 (increasePinFails before asking PIN)
* 74163bf0fd0d002eb4b6ba4c3042095138cc1d0d (rework pin handling)
