### ISSUE TITLE
Put STAGE_2 after confirmations

### ISSUE THREAD

**Issue by runn1ng** [trezor/trezor-mcu#64]
The "STAGE_2" streaming can take a long time, especially with really big previous transactions. Would it be possible to put the STAGE_2 after the confirmations? So rather than "wait a long time - confirm - wait a long time", the scenario would be "confirm - wait a long time".

This might probably not be possible, I am just interested why :)

**Comment by prusnak** [comment]
There are two types of confirmations. Confirm Output and Confirm Tx (with fee). The latter could not be done before all prevtxs are streamed in (that's the whole purpose of stage 2 - to calculate the fee which is then shown in Confirm Tx dialog). Or is there something I am missing?

**Comment by runn1ng** [comment]
ok
