### ISSUE TITLE
Bootloader: Show hash of the firmware in the unofficial warning screen

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-mcu#65]
That allows one to upload and use their own custom built firmware without being worried that it's been replaced with an evil firmware. (Currently there is no way to tell them apart, because they show the same warning, without hash).

**Comment by bgok** [comment]
👍

**Comment by prusnak** [comment]
Implemented in https://github.com/trezor/trezor-mcu/commit/63bc16d375461af744f36c8cf83df21d03267671 and https://github.com/trezor/trezor-mcu/commit/fa0b238b4516d2b142f7c0c318ce1f909bb9847b
