### ISSUE TITLE
Initialize while listing seeds for device setup doesn't return features

### ISSUE THREAD

**Issue by runn1ng** [trezor/trezor-mcu#68]
(similar to issue #67)

When the device is listing seed words in device setup, computer should be able to reset the device with Initialize message.

It doesn't work and the Initialize never returns any features. The computer is expecting them and hangs.

Example in python, similar to examples in #67 
* https://gist.github.com/runn1ng/d4cbd29452ed81501c39

(run with *un*initialized device)

**Comment by runn1ng** [comment]
The same bug is *not* present in device recovery

**Comment by jhoenicke** [comment]
Isn't a `fsm_sendFailure` in `reset.c` line 146 (between layoutHome() and return) enough to solve this issue?

**Comment by prusnak** [comment]
Good find, Jochen! Thanks! Fixed in https://github.com/trezor/trezor-mcu/commit/633024a9933c2f6b672ac6ec3e7e69c384ec90be
