### ISSUE TITLE
Cache BIP39 results with different passphrases

### ISSUE THREAD

**Issue by prusnak** [trezor/trezor-mcu#71]
So we don't have to stretch everytime we call Initialize.

**Comment by bgok** [comment]
Are you talking about permanent storage or in RAM? Permanent storage would make the seed+password more vulnerable to attacks on the device.

**Comment by prusnak** [comment]
RAM

**Comment by prusnak** [comment]
implemented in https://github.com/trezor/trezor-crypto/commit/9a8e982153d3acab75c0707e3c88872f6c5c781c and https://github.com/trezor/trezor-mcu/commit/285f06fe2f820b2483b3da7df2360025d8a9dc87
