### ISSUE TITLE
Bootloader exceeds 32kb 

### ISSUE THREAD

**Issue by karek314** [trezor/trezor-mcu#73]
I can't find way or previous commits to go down below 32kb with bootloader. I have tried several ways to compile, it appears that **trezor-crypto** is too big even compiling with **USE_PRECOMPUTED_CP=0**

**Comment by prusnak** [comment]
Edit `Makefile` and change
```
OPTFLAGS  = -O3 -g -DNDEBUG
```
to
```
OPTFLAGS  = -Os -g -DNDEBUG
```.

**Comment by karek314** [comment]
Worked, thanks :)
