### ISSUE TITLE
support nlocktime different than 0

### ISSUE THREAD

**Issue by greenaddress** [trezor/trezor-mcu#77]
https://github.com/trezor/trezor-mcu/blob/d77152b5a5ac88a8804373d3d9b1d1f65e5cbe4c/firmware/signing.c#L55
doesn't seem it supports non-0 lock_time

https://github.com/trezor/trezor-mcu/blob/d77152b5a5ac88a8804373d3d9b1d1f65e5cbe4c/firmware/signing.c#L255

is there a plan for TREZOR to support nlocktime?

**Comment by prusnak** [comment]
Good find! Implemented in https://github.com/trezor/trezor-mcu/commit/d8aeb63854e102bea0fcd75f3d2a816d6db3fde8
